language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
# uncomment this line if your project needs to run something other than `rake`:
before_script:
  - mysql -e 'create database the_arcadians_test;'
script: bundle exec rspec spec