language: ruby
rvm:
  - 1.9.2
  - 1.9.3
# uncomment this line if your project needs to run something other than `rake`:
before_script:
  - mysql -e 'create database the_arcadians_test;'
  - rake db:migrate
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rspec spec